=== kweaver-ai/isf/Authorization/driveradapters/jsonschema/policy/policy.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "description": "请求体结构定义 - 配置策略",
    "items": {
        "type": "object",
        "required": [
            "accessor",
            "resource",
            "operation"
        ],
        "properties": {
            "accessor": {
                "type": "object",
                "description": "访问者信息",
                "required": [
                    "id",
                    "type"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "user",
                            "department",
                            "group",
                            "role",
                            "app"
                        ]
                    }
                }
            },
            "resource": {
                "type": "object",
                "description": "资源信息",
                "required": [
                    "id",
                    "name",
                    "type"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "description": "资源类型"
                    }
                }
            },
            "operation": {
                "type": "object",
                "description": "操作",
                "required": [
                    "allow",
                    "deny"
                ],
                "properties": {
                    "allow": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "obligations": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": [
                                            "type_id"
                                        ],
                                        "properties": {
                                            "type_id": {
                                                "type": "string"
                                            },
                                            "id": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "object",
                                                "additionalProperties": true
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "deny": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "condition": {
                "type": "string",
                "description": "条件"
            },
            "expires_at": {
                "type": "string"
            }
        }
    }
}

=== kweaver-ai/isf/Authorization/driveradapters/init_data/policy/policy.json
[
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "00990824-4bf7-11f0-8fa7-865d5643e61f",
            "type": "role",
            "name": "数据管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "list"
                },
                {
                    "id": "create"
                },
                {
                    "id": "modify"
                },
                {
                    "id": "delete"
                },
                {
                    "id": "view"
                },
                {
                    "id": "manual_exec"
                },
                {
                    "id": "run_statistics"
                },
                {
                    "id": "run_with_app"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "dataflow_page:o11y",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "00990824-4bf7-11f0-8fa7-865d5643e61f",
            "type": "role",
            "name": "数据管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "display"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "dataflow_page:o11y",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "3fb94948-5169-11f0-b662-3a7bdba2913f",
            "type": "role",
            "name": "AI管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "display"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "3fb94948-5169-11f0-b662-3a7bdba2913f",
            "type": "role",
            "name": "AI管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "dataflow_page:o11y",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "1572fb82-526f-11f0-bde6-e674ec8dde71",
            "type": "role",
            "name": "应用管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "display"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "data_flow",
            "name": "数据流"
        },
        "accessor": {
            "id": "1572fb82-526f-11f0-bde6-e674ec8dde71",
            "type": "role",
            "name": "应用管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "operator",
            "name": "算子"
        },
        "accessor": {
            "id": "3fb94948-5169-11f0-b662-3a7bdba2913f",
            "type": "role",
            "name": "AI管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create"
                },
                {
                    "id": "modify"
                },
                {
                    "id": "delete"
                },
                {
                    "id": "view"
                },
                {
                    "id": "publish"
                },
                {
                    "id": "unpublish"
                },
                {
                    "id": "authorize"
                },
                {
                    "id": "public_access"
                },
                {
                    "id": "execute"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "tool_box",
            "name": "工具箱"
        },
        "accessor": {
            "id": "3fb94948-5169-11f0-b662-3a7bdba2913f",
            "type": "role",
            "name": "AI管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create"
                },
                {
                    "id": "modify"
                },
                {
                    "id": "delete"
                },
                {
                    "id": "view"
                },
                {
                    "id": "publish"
                },
                {
                    "id": "unpublish"
                },
                {
                    "id": "authorize"
                },
                {
                    "id": "public_access"
                },
                {
                    "id": "execute"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "mcp",
            "name": "mcp"
        },
        "accessor": {
            "id": "3fb94948-5169-11f0-b662-3a7bdba2913f",
            "type": "role",
            "name": "AI管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create"
                },
                {
                    "id": "modify"
                },
                {
                    "id": "delete"
                },
                {
                    "id": "view"
                },
                {
                    "id": "publish"
                },
                {
                    "id": "unpublish"
                },
                {
                    "id": "authorize"
                },
                {
                    "id": "public_access"
                },
                {
                    "id": "execute"
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "operator",
            "name": "算子"
        },
        "accessor": {
            "id": "00990824-4bf7-11f0-8fa7-865d5643e61f",
            "type": "role",
            "name": "数据管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create",
                    "name": ""
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "mcp",
            "name": "mcp"
        },
        "accessor": {
            "id": "00990824-4bf7-11f0-8fa7-865d5643e61f",
            "type": "role",
            "name": "数据管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create",
                    "name": ""
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "tool_box",
            "name": "工具箱"
        },
        "accessor": {
            "id": "00990824-4bf7-11f0-8fa7-865d5643e61f",
            "type": "role",
            "name": "数据管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create",
                    "name": ""
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "mcp",
            "name": "mcp"
        },
        "accessor": {
            "id": "1572fb82-526f-11f0-bde6-e674ec8dde71",
            "type": "role",
            "name": "应用管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create",
                    "name": ""
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "tool_box",
            "name": "工具箱"
        },
        "accessor": {
            "id": "1572fb82-526f-11f0-bde6-e674ec8dde71",
            "type": "role",
            "name": "应用管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "create",
                    "name": ""
                }
            ],
            "deny": []
        }
    },
    {
        "expires_at": "1970-01-01T08:00:00+08:00",
        "resource": {
            "id": "*",
            "type": "agent",
            "name": "智能体"
        },
        "accessor": {
            "id": "1572fb82-526f-11f0-bde6-e674ec8dde71",
            "type": "role",
            "name": "应用管理员"
        },
        "operation": {
            "allow": [
                {
                    "id": "publish_to_be_skill_agent"
                },
                {
                    "id": "publish_to_be_api_agent"
                },
                {
                    "id": "create_system_agent"
                },
                {
